version: '3.9'

services:
  backend:
    build: .
    container_name: django_app
    command: ["gunicorn", "lms.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=True
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  frontend:
    build: ./client
    container_name: react_app
    volumes:
      - frontend_build:/usr/share/nginx/html
    ports:
      - "3000:3000"
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/http.conf:/etc/nginx/conf.d/http.conf:ro
      - ./nginx/templates/https.conf:/etc/nginx/templates/https.conf:ro
      - frontend_build:/usr/share/nginx/html
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend
      - frontend
    restart: always
    entrypoint: ["/entrypoint.sh"]

volumes:
  postgres_data:
  static_volume:
  media_volume:
  frontend_build:
