# Generated by Django 5.1.6 on 2025-02-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="group.group"
            ),
        ),
    ]
