# Generated by Django 5.1.6 on 2025-02-12 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("group", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="group_students", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
