# Generated by Django 5.1.6 on 2025-02-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="course_number",
            new_name="year_number",
        ),
    ]
